[package]
name = "actor_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.19", features = ["default", "wayland"] }
shared = { path = "../shared" }
client_core = { path = "../client_core" }
bevy_panorbit_camera = "0.35"
bevy_hanabi = "0.19"
rfd = "0.17"
meshopt = "0.6"
ron = "0.12.1"
image = "0.25"
chrono = "0.4"
futures-lite = "2.6.1"
