[package]
name = "actor_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["default", "wayland"] }
shared = { path = "../shared" }
client_core = { path = "../client_core" }
bevy_mod_picking = { version = "0.20", features = ["selection", "highlight", "backend_raycast", "backend_bevy_ui"] }
bevy_panorbit_camera = "0.20"
bevy_hanabi = "0.13"
rfd = "0.14"
meshopt = "0.3"
ron = "0.12.1"
image = "0.25"
chrono = "0.4"
futures-lite = "2.6.1"
